#!/bin/bash

# Deploy Commands for Mobile Phone Management System
# Run these commands step by step

echo "🚀 Mobile Phone Management System - Deployment Guide"
echo "=================================================="

echo ""
echo "Step 1: Create MongoDB Atlas Database"
echo "--------------------------------------"
echo "1. Go to https://www.mongodb.com/atlas/database"
echo "2. Create a free cluster (M0 Sandbox)"
echo "3. Create a database user"
echo "4. Get your connection string"
echo ""
echo "Connection String Format:"
echo "mongodb+srv://username:password@cluster.mongodb.net/phone_management?retryWrites=true&w=majority"
echo ""

echo "Step 2: Push Code to GitHub"
echo "---------------------------"
echo "Run these commands:"
echo ""
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit - Phone Management System'"
echo "git branch -M main"
echo "git remote add origin https://github.com/your-username/phone-management.git"
echo "git push -u origin main"
echo ""

echo "Step 3: Deploy Backend on Railway"
echo "---------------------------------"
echo "1. Go to https://railway.app"
echo "2. Sign up/Login with GitHub"
echo "3. New Project -> Deploy from GitHub repo"
echo "4. Select your repository"
echo "5. Add these Environment Variables:"
echo ""
echo "   MONGODB_URI=your_mongodb_atlas_connection_string"
echo "   DB_NAME=phone_management"
echo "   PORT=8080"
echo "   ENVIRONMENT=production"
echo "   FRONTEND_URL=https://your-frontend.vercel.app"
echo ""
echo "6. Railway will automatically deploy your app"
echo ""

echo "Step 4: Deploy Frontend on Vercel"
echo "---------------------------------"
echo "1. Go to https://vercel.com"
echo "2. Sign up/Login with GitHub"
echo "3. New Project -> Import Git Repository"
echo "4. Select your repository"
echo "5. Set Root Directory to 'frontend'"
echo "6. Add Environment Variable:"
echo ""
echo "   API_BASE_URL=https://your-backend.railway.app/api/v1"
echo ""
echo "7. Deploy!"
echo ""

echo "Step 5: Initialize Database"
echo "---------------------------"
echo "1. Open MongoDB Compass or Atlas Web UI"
echo "2. Connect to your cluster"
echo "3. Run the scripts from the 'scripts' folder:"
echo "   - create-indexes.js"
echo "   - seed-data.js"
echo ""

echo "Step 6: Setup Telegram Bot (Optional)"
echo "------------------------------------"
echo "1. Message @BotFather on Telegram"
echo "2. Create new bot: /newbot"
echo "3. Get your bot token"
echo "4. Add to Railway Environment Variables:"
echo ""
echo "   TELEGRAM_BOT_TOKEN=your_bot_token"
echo ""

echo "🎉 Deployment Complete!"
echo "======================"
echo ""
echo "Your app should be available at:"
echo "- Frontend: https://your-project.vercel.app"
echo "- Backend: https://your-project.railway.app"
echo "- API Health: https://your-project.railway.app/health"
echo ""
echo "Free Tier Limitations:"
echo "- Railway: 512MB RAM, 500 hours/month"
echo "- Vercel: 100GB bandwidth/month"
echo "- MongoDB Atlas: 512MB storage"
echo ""
echo "Need help? Check deploy-railway.md for detailed instructions!"